### ISSUE TITLE
编辑活动页面 404

### ISSUE THREAD

**Issue by wangrunlin** [kaiyuanshe/OpenHackathon-Web#123]
代码更新不兼容旧代码

**Comment by wangrunlin** [comment]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/64216877/197395468-cc8ff3b6-ff2b-4a85-94c5-5a8e58ffbad7.png">

**Comment by wangrunlin** [comment]
https://github.com/kaiyuanshe/OpenHackathon-Web/blob/8e0f0cbbe5bf0ef4bfc5b814c02d13a72edaf3d2/pages/activity/%5Bname%5D/manage/edit.tsx#L13

似乎我的 Devtools Network 中并没有看到这个请求

**Comment by TechQuery** [comment]
> https://github.com/kaiyuanshe/OpenHackathon-Web/blob/8e0f0cbbe5bf0ef4bfc5b814c02d13a72edaf3d2/pages/activity/%5Bname%5D/manage/edit.tsx#L13
> 
> 似乎我的 Devtools Network 中并没有看到这个请求

因为它在服务端运行

**Comment by TechQuery** [comment]
这个问题是因为活动未经**平台管理员**审核上线，后端接口返回 404 导致，并非前端代码的 bug：

![image](https://user-images.githubusercontent.com/19969570/197861788-0079bb4f-9efa-4eac-9b75-7b3e00a44bb7.png)

**Comment by TechQuery** [comment]
活动基本信息编辑页无需服务端渲染，应由客户端控制权限，此处需重构：
https://github.com/kaiyuanshe/OpenHackathon-Web/blob/8e0f0cbbe5bf0ef4bfc5b814c02d13a72edaf3d2/pages/activity/%5Bname%5D/manage/edit.tsx#L8-L21
