### ISSUE TITLE
优化小屏幕适配

### ISSUE THREAD

**Issue by TechQuery** [kaiyuanshe/OpenHackathon-Web#154]
大家可以把自己发现的各种屏幕适配 bug 截图贴在这里

![34854da61598fd8a.png](https://user-images.githubusercontent.com/19969570/209129455-5709f381-f438-4b09-8de1-c1b0545deeb0.png)

**Comment by wangrunlin** [comment]
内容不能输入换行

![img_v2_7031f1b9-e5bb-42e8-84f6-845bbdab033g](https://user-images.githubusercontent.com/64216877/221497552-f09c51d1-05ed-4b52-aba1-8e31962e6444.jpg)

**Comment by tianheg** [comment]
@TechQuery 水歌，我认领了这个 issue，拉我进一下组织

**Comment by tianheg** [comment]
## 问题跟踪TODOList

### 小屏优化相关

- [ ] 

### 其他

- [ ] 在创建活动页面 `/activity/create`，活动名称的 placeholder 重复，解决办法：删除/描述活动命名的要求（对应代码 [components/Activity/ActivityEditor.tsx](https://github.com/kaiyuanshe/OpenHackathon-Web/blob/fbdb3fe092a38f186f6079493358221dcf164523/components/Activity/ActivityEditor.tsx#L119)）
- [ ] 在创建活动页面 `/activity/create`，关于“必填”一词的使用，活动ID、活动地址、活动简介、活动详情都需要填写，但都没有用“必填”说明，解决办法：对需要填写而没有“必填”字样的条目添加“必填”字样（但这样又显得重复，字数过多，能否把“必填”改为红色星号？）（对应代码 [components/Activity/ActivityEditor.tsx](https://github.com/kaiyuanshe/OpenHackathon-Web/blob/fbdb3fe092a38f186f6079493358221dcf164523/components/Activity/ActivityEditor.tsx) 多处）

**Comment by tianheg** [comment]
@wangrunlin 你的这个页面是在哪里，需要管理员权限吗

**Comment by TechQuery** [comment]
> 内容不能输入换行
> 
> ![img_v2_7031f1b9-e5bb-42e8-84f6-845bbdab033g](https://user-images.githubusercontent.com/64216877/221497552-f09c51d1-05ed-4b52-aba1-8e31962e6444.jpg)

@tianheg 活动管理后台的『公告』

**Comment by tianheg** [comment]
@TechQuery 现在有空吗，我需要本地上线活动的权限
