### ISSUE TITLE
非 GitHub 账号无法正常跳转

### ISSUE THREAD

**Issue by PapayaHUANG** [kaiyuanshe/OpenHackathon-Web#170]
![图片展示](https://raw.githubusercontent.com/PapayaHUANG/images/main/img/WechatIMG598.png)
如图，如果通过手机登陆的管理账号，无法正常跳转显示“云开发环境”页面。

**Comment by TechQuery** [comment]
手机号注册/登录的人一般没有关联 GitHub 账号，自然取不到相关数据，此处代码要做一个空对象防御。

**Comment by PapayaHUANG** [comment]
如果合并了 #175 这个 PR，这个路由就改掉用我们自己的 API，所以就完美的绕开了这个 issue 的问题。

另外测试了用手机号账号登陆 `team` 路由下的云管理：

- 如果是通过页面按钮实现页面跳转：
![image](https://github.com/kaiyuanshe/OpenHackathon-Web/assets/70144378/dc4cc85f-880e-46a9-bc88-a9cefb498c3e)
没有按钮跳转到对应页面

- 如果是直接在地址栏输入的结果：
![image](https://github.com/kaiyuanshe/OpenHackathon-Web/assets/70144378/902e77bd-ee76-44f6-a5e4-35b6a42339a3)

@TechQuery

**Comment by TechQuery** [comment]
> 另外测试了用手机号账号登陆 `team` 路由下的云管理：
> 
> - 如果是通过页面按钮实现页面跳转：
> ![image](https://github.com/kaiyuanshe/OpenHackathon-Web/assets/70144378/dc4cc85f-880e-46a9-bc88-a9cefb498c3e)
> 没有按钮跳转到对应页面
> 
> - 如果是直接在地址栏输入的结果：
> ![image](https://github.com/kaiyuanshe/OpenHackathon-Web/assets/70144378/902e77bd-ee76-44f6-a5e4-35b6a42339a3)
> 
> @TechQuery

@PapayaHUANG 这个手机号账号应该不是这个团队的管理员，我才意识到云开发环境的页面是在团队管理页，按理说应该每个团队成员登录后都可以看到，所以可能需要移动页面位置。

**Comment by TechQuery** [comment]
> 如果合并了 #175 这个 PR，这个路由就改掉用我们自己的 API，所以就完美的绕开了这个 issue 的问题。

点击『授权全部队友』按钮的时候还是需要前端去调 GitHub API。
