### ISSUE TITLE
优化 UI 细节

### ISSUE THREAD

**Issue by YeSuX** [kaiyuanshe/OpenHackathon-Web#187]

**Comment by YeSuX** [comment]
1. <img width="740" alt="image" src="https://github.com/kaiyuanshe/OpenHackathon-Web/assets/44074974/dd69bf75-45b5-479b-aa3d-2478d09a5514">
活动团队团队card没有对齐

**Comment by YeSuX** [comment]
<img width="325" alt="image" src="https://github.com/kaiyuanshe/OpenHackathon-Web/assets/44074974/23dff508-8ca7-4c09-8393-834f5627a7f9">
2. 手机端两个section之间没有间距

**Comment by YeSuX** [comment]
3. 关注活动中时间无法全部显示
<img width="558" alt="image" src="https://github.com/kaiyuanshe/OpenHackathon-Web/assets/44074974/d14f62ce-4dcc-4be4-a163-9ea8a0cd70c7">

**Comment by YeSuX** [comment]
4. 轮播图没有限定高度，高度会随着图片的变化而变化
<img width="1172" alt="image" src="https://github.com/kaiyuanshe/OpenHackathon-Web/assets/44074974/9a2f5961-f3e3-4fff-8d7a-76c5a48175d9">

**Comment by huoyueyuyuan** [comment]
> 3. 关注活动中时间无法全部显示
> 
> <img alt="image" width="558" src="https://user-images.githubusercontent.com/44074974/253727085-d14f62ce-4dcc-4be4-a163-9ea8a0cd70c7.png">

已经修复。
修复分支 ：https://github.com/kaiyuanshe/OpenHackathon-Web/pull/195

**Comment by huoyueyuyuan** [comment]
> 4. 轮播图没有限定高度，高度会随着图片的变化而变化
> 
> <img alt="image" width="1172" src="https://user-images.githubusercontent.com/44074974/253727563-9a2f5961-f3e3-4fff-8d7a-76c5a48175d9.png">

已经修复，并合入main。
修复分支 ：https://github.com/kaiyuanshe/OpenHackathon-Web/pull/195
