### ISSUE TITLE
个人主页 GitHub 链接更新错误

### ISSUE THREAD

**Issue by YeSuX** [kaiyuanshe/OpenHackathon-Web#189]
个人主页中，GitHub 登陆后，如果修改了用户资料名称，GitHub 跳转会有问题。

![f2fd8960-19db-4e44-8064-034196e6181c](https://github.com/kaiyuanshe/OpenHackathon-Web/assets/44074974/6e018207-d797-4c60-bc8a-f00ea13b9979)

**Comment by TechQuery** [comment]
这是因为目前接口数据中没有固定的字段存储各第三方平台的用户 ID，因此暂时无解。
