### ISSUE TITLE
对接后端 v5 API

### ISSUE THREAD

**Issue by TechQuery** [kaiyuanshe/OpenHackathon-Web#204]
## 核心需求

将**后端接口封装包** `mobx-restful` 替换为 [`mobx-strapi`](https://github.com/idea2app/MobX-RESTful/tree/main/wrapper/Strapi)

## 接口文档

https://hackathon-server.kaiyuanshe.cn/documentation

**Comment by luojiyin1987** [comment]
`mobx-restful-table`  跟 `mobx-restful` 是否有依赖关系？    [mobx-strapi](https://github.com/idea2app/MobX-RESTful/tree/main/wrapper/Strapi) 是否可以直接替换 ？

**Comment by TechQuery** [comment]
> `mobx-restful-table` 跟 `mobx-restful` 是否有依赖关系？ `mobx-strapi` 是否可以直接替换 ？

有；可，但需要修改接口路径、数据类型。

**Comment by TechQuery** [comment]
Strapi API 的 HTTP 客户端已接好，可直接引用：
https://github.com/kaiyuanshe/OpenHackathon-Web/blob/035110a09be2377bfcd32525374404e477791978/models/User/Session.ts#L13-L26
