### ISSUE TITLE
团队编辑页

### ISSUE THREAD

**Issue by TechQuery** [kaiyuanshe/OpenHackathon-Web#21]
@juniwang 创建团队的后端接口是怎样的？

**Comment by Coderhypo** [comment]
## API 整理

### 当前用户团队

Path：`/api/team/my`
Method：`GET`

### 团队管理

Path：`/api/team`

#### 查看团队信息

Method：`GET`

参数

| 参数 | 含义 |
|----|----|
|  id  |  团队 id  |

#### 创建团队

Method：`POST`

> 未找到实现

#### 更新团队信息

Method：`PUT`

参数

| 参数 | 含义 |
|----|----|
|  id  |  团队 id  |
|  name  |  团队名称  |
|  dev_plan  |  开发计划  |

#### 删除团队信息

Method：`DELETE`

参数

| 参数 | 含义 |
|----|----|
|  id  |  团队 id  |

### 黑客松团队

#### 团队列表

Path：`/api/hackathon/team/list`
Method：`GET`

参数

| 参数 | 含义 |
|----|----|
|  name  |  团队名  |
|  number  |  返回个数  |

#### 团队分数

Path：`/api/team/score`

##### 分数信息

Method：`GET`

参数

| 参数 | 含义 |
|----|----|
|  team_id  |  团队 id  |

##### 新建分数

Method：`POST`

参数

| 参数 | 含义 |
|----|----|
|  team_id  |  团队 id  |
|  reason  | 原因/备注  |

##### 更新分数

Method：`PUT`

参数

| 参数 | 含义 |
|----|----|
|  team_id  |  团队 id  |
|  reason  | 原因/备注  |

### Team Show

Path：`/api/team/show`

#### Get Info

Method：`GET`

参数

| 参数 | 含义 |
|----|----|
|  team_id  |  团队 id  |

#### New Show

Method：`POST`

参数

| 参数 | 含义 |
|----|----|
|  note  |  work describe  |
|  type  |  work type  |
|  uri  |  work uri  |

#### New Show

Method：`DELETE`

参数

| 参数 | 含义 |
|----|----|
|  id  |  show id  |

### 团队成员管理

#### 查看成员

Path：`/api/team/member/list`
Method：`GET`

#### 成员管理

Path：`/api/team/member`

##### 加入团队

Method：`POST`

参数

| 参数 | 含义 |
|----|----|
|  team_id  |  团队 id  |

##### 更新团队成员状态

Method：`PUT`

参数

| 参数 | 含义 |
|----|----|
|  team_id  |  团队 id  |
|  user_id  |  用户 id  |
|  status  |  状态  |

##### 离开团队

Method：`DELETE`

参数

| 参数 | 含义 |
|----|----|
|  team_id  |  团队 id  |
|  user_id  |  用户 id  |

#### 发送邮件

Path：`/api/team/email`
Method：`PUT`

参数

| 参数 | 含义 |
|----|----|
|  id  |  团队 id  |

**Comment by TechQuery** [comment]
## 功能

在以下页面上部右侧**活动信息**板块下方加一个「创建团队」链接按钮，跳转到新开发的表单页：
https://hackathon.kaiyuanshe.cn/#activity?name=test4

## 接口

（本 issue 前面的接口是 Python v2 的，已作废）

![image](https://user-images.githubusercontent.com/19969570/122753307-a6469a80-d2c4-11eb-8fcb-f908328a5e4e.png)
