### ISSUE TITLE
裁判设置页

### ISSUE THREAD

**Issue by TechQuery** [kaiyuanshe/OpenHackathon-Web#51]
## 主要功能

- [ ] 裁判列表
- [ ] 添加裁判：从系统现有用户中选择

## 后端接口

https://hackathon-api.kaiyuanshe.cn/swagger/index.html#operations-OpenHackathon-put_v2_hackathon__hackathonName__judge__userId_

**Comment by stevending1st** [comment]
> * 从系统现有用户中选择

没有获取所有用户的接口......

**Comment by juniwang** [comment]
选择不太友好，可以考虑用搜索

**Comment by TechQuery** [comment]
> 选择不太友好，可以考虑用搜索

搜索也得有个带筛选参数的列表接口啊

**Comment by stevending1st** [comment]
![image](https://user-images.githubusercontent.com/23376142/152378721-3811c8e9-072d-4c81-b817-2fbd3cc33e4f.png)

所有用户就是上面的接口吗？

**Comment by stevending1st** [comment]
@juniwang 谢谢您为这个项目付出的辛劳，但是，有些接口似乎因为语言差异和单词使用习惯问题，而难以找到。
例如，在本 issue 中，用户获取 API 并不明确。是否在 API 文档中适当添加中文解释，或者一些业务逻辑内容，帮助其他开发者更好参与项目。

**Comment by juniwang** [comment]
这个是获取管理员的，搜索用户的接口暂时还没有，得等后端添加，暂定1周吧。
中文注释是个好主意，我们研究看看怎么支持多语言

**Comment by juniwang** [comment]
搜索用户api加好了: `/v2/api/search`:
![image](https://user-images.githubusercontent.com/8814383/153525219-784b1cc8-d984-4ab5-9e93-f831569dce93.png)
