### ISSUE TITLE
6. 报名-后台端界面-支持显示所有报名信息

### ISSUE THREAD

**Issue by stevending1st** [kaiyuanshe/OpenHackathon-Web#94]
支持显示所有报名信息

**Comment by TechQuery** [comment]
他们应该没注意每行「姓名」是一个可点击的链接，会出弹框：

![1664149172213.jpg](https://user-images.githubusercontent.com/19969570/192170772-275e80ee-74a0-4757-90d9-1ccf9260058b.jpg)
