### ISSUE TITLE
3. 报名-学生端界面-报名时自定义信息

### ISSUE THREAD

**Issue by stevending1st** [kaiyuanshe/OpenHackathon-Web#95]
基础需求
- 输入姓名、学校、手机号、邮箱等信息后，点击提交，完成报名；

进阶需求
- 报名时自定义信息

**Comment by stevending1st** [comment]
https://github.com/kaiyuanshe/OpenHackathon-Web/blob/main/models/Question.ts

**Comment by scarqin** [comment]
* 前端改一下配置文件
* 后端暂时不需要支持
下个阶段做进阶需求需要后端支持

**Comment by TechQuery** [comment]
## 后端接口

![Image](https://user-images.githubusercontent.com/19969570/200171017-8d726a2b-bc97-4c12-8f64-e3ffd70395f4.png)

**Comment by alili** [comment]
```
curl https://hackathon-api.kaiyuanshe.cn/v2/hackathon/code4city/questionnaire

{
  "type":"https://httpstatuses.com/404",
  "title":"Not Found",
  "status":404,
  "detail":"No associate questionnaire cannot be found.",
  "traceId":"|42a787fa-4713ba8bd50b396b.1.20ef8d0b_"
}
```

接口访问有问题

**Comment by TechQuery** [comment]
> ```
> curl https://hackathon-api.kaiyuanshe.cn/v2/hackathon/code4city/questionnaire
> 
> {
>   "type":"https://httpstatuses.com/404",
>   "title":"Not Found",
>   "status":404,
>   "detail":"No associate questionnaire cannot be found.",
>   "traceId":"|42a787fa-4713ba8bd50b396b.1.20ef8d0b_"
> }
> ```
> 
> 接口访问有问题

需要先创建题目：
![image](https://user-images.githubusercontent.com/19969570/204131524-6d291ee5-58c0-4619-ad4d-09c859777eec.png)

**Comment by alili** [comment]
那需要在创建活动的时候，同时创建这个问卷，指定有哪些字段？

**Comment by TechQuery** [comment]
> 那需要在创建活动的时候，同时创建这个问卷，指定有哪些字段？

也可以在报名时检测是否有问卷，没有就直接报名成功，再在活动管理页做个问卷编辑页。
