### ISSUE TITLE
12. 支持作品导出功能

### ISSUE THREAD

**Issue by stevending1st** [kaiyuanshe/OpenHackathon-Web#96]
提交-后台端界面-支持作品导出功能； 提交-后台端界面-支持作品导出功能

**Comment by scarqin** [comment]
后端已经支持 @juniwang ？
前端需要加入导出按钮。

**Comment by scarqin** [comment]
后端已经支持 @juniwang ？
前端需要加入导出按钮。

**Comment by scarqin** [comment]
现阶段可以先支持查看单个作品，后续再支持批量导出。
@TechQuery @scarqin 敲设计

**Comment by juniwang** [comment]
后端已经增加导出接口。接口返回的excel，只包含作品链接。如昨晚讨论，如果需要到处文件内容，则需要另外的接口
