### ISSUE TITLE
8. 支持报名信息导出

### ISSUE THREAD

**Issue by stevending1st** [kaiyuanshe/OpenHackathon-Web#98]

**Comment by juniwang** [comment]
接口已发布. reportType暂时只有enrollments，更多reportType正在添加.

访问方式1：使用query（可以做为下载链接）：`https://hackathon-api.kaiyuanshe.cn/v2/hackathon/foo/report?reportType=enrollments&token=<TOKEN>`

访问方式2：Authorization header：
```
curl -X 'GET' \
  'https://hackathon-api.kaiyuanshe.cn/v2/hackathon/foo/report' \
  -H 'Authorization: token <TOKEN>'
```

![image](https://user-images.githubusercontent.com/8814383/192143797-96d4ef21-78b7-473b-a3df-ce1aa20267ef.png)
