### ISSUE TITLE
7. 活动报名

### ISSUE THREAD

**Issue by stevending1st** [kaiyuanshe/OpenHackathon-Web#99]
基础需求：
- 加入团队

进阶需求
- 支持小组形式进行报名，包括输入小组名称、添加队员、队伍简介等

**Comment by scarqin** [comment]
已经支持报名
![Image](https://user-images.githubusercontent.com/15225835/192775016-9440e363-3408-403a-afe2-38c1bed81294.png)
还差加入团队
